cloud:
  aws:
    region:
      static: us-east-2
      auto: false
    credentials:
      access-key: AKIAXMFZED3YA7H3Z2AQ
      secret-key: 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
    end-point:
      uri: https://sqs.us-east-2.amazonaws.com/507194384112/sqs-queue
    stack:
      auto: false


server:
  port: 8023